apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: cicd-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: argo-cicd-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-cd-from-webhook-
              spec:
                arguments:
                  parameters:
                    - name: branch
                      value: main
                    - name: dockerRepo
                      value: docker.io/qdnqn/argo-workflows:1.0.0
                workflowTemplateRef:
                  name: cicd-workflow-template
          parameters:
            - src:
                dependencyName: cicd-dep
                dataKey: body.branch
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: cicd-dep
                dataKey: body.image
              dest: spec.arguments.parameters.1.value