---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: go-api-role
  namespace: go-api
rules:
  - apiGroups:
      - ""
      - "apps"
      - "networking.k8s.io"
    verbs:
      - "*"
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor-role-binding
  namespace: go-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: go-api-role
subjects:
  - kind: ServiceAccount
    name: workflow-executor-sa
    namespace: argo-events
