apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  name: workflow-executor-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor-role
  namespace: argo-events
rules:
  - apiGroups:
      - ""
    verbs:
      - "*"
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor-role-binding
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-executor-role
subjects:
  - kind: ServiceAccount
    name: workflow-executor-sa
    namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-creator
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "create"
      - "get"
      - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-creator
subjects:
  - kind: ServiceAccount
    name: workflow-executor-sa
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: namespace-creator
  apiGroup: rbac.authorization.k8s.io